// Two-level cache for Bible chapter JSON files:
//  1. In-memory Map   — instant within the current page session
//  2. Cache API       — persisted across navigations / page reloads
//
// Architecture: HYBRID
//  - The SSG reader fetches individual chapters via `fetchChapter()` (unchanged).
//  - The search modal and offline downloader use `fetchBook()`, which loads
//    a single per-book JSON file containing ALL chapters for that book.
//    This reduces the request count from 1,189 → 66 per Bible version.
//
// The per-book JSON files are generated by `scripts/generate-book-json.py`.
// Their structure is: { "1": [{ verse, text }, ...], "2": [...], ... }
//
// This module has no React dependencies and can be imported by any client module.
// All browser-API calls are guarded with `typeof` checks so SSR never throws.

import type { Verse } from '@/lib/bible/types'

const CACHE_NAME = 'veobible-bible-data'

// In-memory layer: URL → verse array
const memCache = new Map<string, Verse[]>()

// ── URL helpers ───────────────────────────────────────────────────────────────

export function chapterUrl(
  lang: string,
  version: string,
  bookId: string,
  chapter: number,
): string {
  return `/bible-data/${lang}/${version}/${bookId}/${chapter}.json`
}

export function bookUrl(lang: string, version: string, bookId: string): string {
  return `/bible-data/${lang}/${version}/${bookId}.json`
}

// ── Cache API helpers ─────────────────────────────────────────────────────────

async function openCache(): Promise<Cache | null> {
  if (typeof caches === 'undefined') return null
  try {
    return await caches.open(CACHE_NAME)
  } catch {
    return null
  }
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Fetch a chapter's verses, falling through the two-level cache.
 *
 * Lookup order: memory → Cache API → network (stores result in both layers).
 *
 * Used by the SSG reader for individual chapter rendering.
 * In production the Service Worker (next-pwa / Workbox) intercepts the
 * network fetch and returns from its own pre-cache — the "network" hop
 * is already effectively instant.
 */
export async function fetchChapter(
  lang: string,
  version: string,
  bookId: string,
  chapter: number,
  signal?: AbortSignal,
): Promise<Verse[]> {
  const url = chapterUrl(lang, version, bookId, chapter)

  // 1. Memory hit — fastest path
  const memHit = memCache.get(url)
  if (memHit) return memHit

  // 2. Cache API hit
  const cache = await openCache()
  if (cache) {
    try {
      const cached = await cache.match(url)
      if (cached) {
        const verses = (await cached.json()) as Verse[]
        memCache.set(url, verses) // promote to memory
        return verses
      }
    } catch {
      // Cache read failed — fall through to network
    }
  }

  // 3. Network fetch (goes through SW in production)
  const res = await fetch(url, signal ? { signal } : undefined)
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`)
  const verses = (await res.json()) as Verse[]

  // Store in both layers (non-blocking, non-critical)
  memCache.set(url, verses)
  if (cache) {
    cache
      .put(
        url,
        new Response(JSON.stringify(verses), {
          headers: { 'Content-Type': 'application/json' },
        }),
      )
      .catch(() => {})
  }

  return verses
}

/**
 * Fetch ALL chapters of a book in a single request using the merged per-book
 * JSON file (`/{bookId}.json`), then populate both cache layers with each
 * chapter individually.
 *
 * Used by the search modal and offline downloader to reduce the request
 * count from 1,189 (per-chapter) to 66 (per-book) per Bible version.
 *
 * If the book is already fully cached in memory, the function returns
 * immediately without any network or Cache API access.
 */
export async function fetchBook(
  lang: string,
  version: string,
  bookId: string,
  chapterCount: number,
  signal?: AbortSignal,
): Promise<Record<number, Verse[]>> {
  // Check if all chapters are already in memory
  const allInMemory = Array.from({ length: chapterCount }, (_, i) => i + 1).every((ch) =>
    memCache.has(chapterUrl(lang, version, bookId, ch)),
  )
  if (allInMemory) {
    const result: Record<number, Verse[]> = {}
    for (let ch = 1; ch <= chapterCount; ch++) {
      result[ch] = memCache.get(chapterUrl(lang, version, bookId, ch))!
    }
    return result
  }

  const url = bookUrl(lang, version, bookId)
  const cache = await openCache()

  // Check Cache API for the per-book file
  if (cache) {
    try {
      const cached = await cache.match(url)
      if (cached) {
        const data = (await cached.json()) as Record<string, Verse[]>
        const result: Record<number, Verse[]> = {}
        for (const [chStr, verses] of Object.entries(data)) {
          const ch = Number(chStr)
          const cUrl = chapterUrl(lang, version, bookId, ch)
          memCache.set(cUrl, verses) // promote each chapter to memory
          result[ch] = verses
        }
        return result
      }
    } catch {
      // Fall through to network
    }
  }

  // Fetch the per-book file from the network
  const res = await fetch(url, signal ? { signal } : undefined)
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`)
  const data = (await res.json()) as Record<string, Verse[]>

  const result: Record<number, Verse[]> = {}

  // Store each chapter in memory and Cache API individually
  for (const [chStr, verses] of Object.entries(data)) {
    const ch = Number(chStr)
    const cUrl = chapterUrl(lang, version, bookId, ch)
    memCache.set(cUrl, verses)
    result[ch] = verses
    if (cache) {
      cache
        .put(
          cUrl,
          new Response(JSON.stringify(verses), {
            headers: { 'Content-Type': 'application/json' },
          }),
        )
        .catch(() => {})
    }
  }

  // Also cache the per-book file itself so next call hits Cache API
  if (cache) {
    cache
      .put(
        url,
        new Response(JSON.stringify(data), {
          headers: { 'Content-Type': 'application/json' },
        }),
      )
      .catch(() => {})
  }

  return result
}

/**
 * Count how many Bible books for a version are cached.
 *
 * We count per-book JSON files (`{bookId}.json`) in the Cache API.
 * Each book file represents all its chapters, so a count of 66 means the
 * entire Bible is cached. Also counts individual chapter files that may
 * have been cached via `fetchChapter` (e.g. while reading).
 *
 * Returns a value in [0, totalBooks] for the offline status indicator.
 */
export async function getCachedBookCount(
  lang: string,
  version: string,
): Promise<number> {
  if (typeof caches === 'undefined') return 0
  try {
    const cache = await openCache()
    if (!cache) return 0
    const keys = await cache.keys()
    const prefix = `/bible-data/${lang}/${version}/`
    // Count per-book files: pathname ends in /{bookId}.json (no slash after bookId)
    return keys.filter((req) => {
      const pathname = new URL(req.url).pathname
      if (!pathname.startsWith(prefix)) return false
      const rest = pathname.slice(prefix.length)
      // per-book file: one segment ending in .json with no nested slash
      return rest.endsWith('.json') && !rest.includes('/') && rest !== 'index.json'
    }).length
  } catch {
    return 0
  }
}

/**
 * Remove all cached entries for a version from both the Cache API and memory.
 */
export async function deleteVersionFromCache(
  lang: string,
  version: string,
): Promise<void> {
  const prefix = `/bible-data/${lang}/${version}/`

  // Clear memory layer
  for (const key of Array.from(memCache.keys())) {
    if (key.startsWith(prefix)) memCache.delete(key)
  }

  // Clear Cache API layer
  if (typeof caches === 'undefined') return
  try {
    const cache = await openCache()
    if (!cache) return
    const keys = await cache.keys()
    await Promise.all(
      keys
        .filter((req) => new URL(req.url).pathname.startsWith(prefix))
        .map((req) => cache.delete(req)),
    )
  } catch {
    // Non-critical
  }
}
